### ISSUE TITLE
SipTwo library issues

### ISSUE THREAD

**Issue by vexagonverp** [jblyberg/SipTwo#1]
Dependency dateformat causing issue Error [ERR_REQUIRE_ESM]: require() of ES Module inside the module
**node_modules\siptwo\dist\lib\helpers\DateTimeHelpers.js:4
const dateFormat = require("dateformat");**

**Comment by jblyberg** [comment]
Looks like that was an issue with the dateformat package. Resolved in 1.0.5. Thanks for the heads-up.
