### ISSUE TITLE
SipTwo Login checksum

### ISSUE THREAD

**Issue by vexagonverp** [jblyberg/SipTwo#2]
Login Response message doesn't support checkSum

**Comment by jblyberg** [comment]
I don't currently have access to a working SIP server, but I believe the change I just made (v1.0.6) should correctly parse the login response for checksum. Let me know if it doesn't. Thanks.

**Comment by vexagonverp** [comment]
The socket received 2 seperated message (the second one is for checksum) leading to error

```
throw new Error('Unsupported identifier: ' + identifier);
    ^

Error: Unsupported identifier: 96
```

**Comment by jblyberg** [comment]
Try 1.0.7. Response ID 96 is a request to resend the self-check request. I've added a response handler for that code so you should be able to check for it in your code.

**Comment by vexagonverp** [comment]
I believe there is something wrong with the checksum algorithm as I tried this algorithm from [stackoverflow](https://stackoverflow.com/questions/30492921/sip2-checksum-calculation-in-javascript) and it worked.

**Comment by jblyberg** [comment]
Just getting back around to this finally. If you are still interested, could you give me a sample SIP2 message string to test with. I suspect that different ILSs implement the checksum slightly differently.

Edit: I've published a new version with the updated checksum code.
