### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'sequence')

### ISSUE THREAD

**Issue by otuoma** [jblyberg/SipTwo#3]
I am testing out the new code release and have setup my project as follows but encounters the error mentioned.

`    
import express, { Request, Response } from 'express';
    import { SipTwo, ISip2ConnectionOptions, IPatronCredentials } from 'siptwo';

    const app = express();
    const PORT = 3000;
    
    const sip2ConnectionOptions: ISip2ConnectionOptions = {
        host: '172.20.22.876',
        port: 6001,
        username: 'DemoUser',
        password: 'DemoUser22',
        institutionId: 'CPL',
        language: 'English',
        timeout: 60,
        maxListeners: 5,
    };
    
    const patronCredentials: IPatronCredentials = {
        patronIdentifier: '123456',
        password: 'DemoUser22',
        institutionId: sip2ConnectionOptions.institutionId
    };
    
    const sipTwo = new SipTwo(sip2ConnectionOptions);
    app.get('/', (req: Request, res: Response) => {
    
        // Inside an async function/method
        (async () => {
            await sipTwo.login();
    
            sipTwo.setPatron(patronCredentials);
            const patronInfo = await sipTwo.requestPatronInformation();
            console.log('patronInfo', patronInfo);
            sipTwo.connection.close();
        })();
    
        res.send('Hello, TypeScript Express!');
    });
    
    app.listen(PORT, () => {
        console.log(`Server is running on port ${PORT}`);
    });
`

Above code throws the error below

`
    TypeError: Cannot read properties of undefined (reading 'sequence')
        at new LoginRequest (C:\projects\siptwo\node_modules\siptwo\src\lib\requests\LoginRequest.ts:8:38)
        at SipTwo.login (C:\projects\siptwo\node_modules\siptwo\src\lib\SipTwo.ts:71:26)
        at C:\projects\siptwo\src\index.ts:29:22
        at Generator.next (<anonymous>)
        at C:\projects\siptwo\src\index.ts:8:71
        at new Promise (<anonymous>)
        at __awaiter (C:\projects\siptwo\src\index.ts:4:12)
        at C:\projects\siptwo\src\index.ts:28:17
        at C:\projects\siptwo\src\index.ts:35:7
        at Layer.handle [as handle_request] (C:\projects\siptwo\node_modules\express\lib\router\layer.js:95:5)

`

@jblyberg

**Comment by jblyberg** [comment]
@otuoma Thank you for the report. The issue seems to have been the `useDefineForClassFields` flag in `tsconfig.json`. Try 1.2.1 for the fix.

**Comment by otuoma** [comment]
Thank you @jblyberg for the good work. One small fix still required. I made this [PR](https://github.com/jblyberg/SipTwo/pull/4/files)
